---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          cp LICENSE LICENSE.md
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            changelog-detailed.md
            changelog.md
            CONTRIBUTING.md
            EDAM_dev.owl
            LICENSE.md
            README.md
